<?php

namespace App\Libraries\Customer;

use App\Entities\SysBaseUser;
use App\Entities\SysCustomer;
use App\Libraries\BaseAuth;
use App\Models\SysCustomers;
use CodeIgniter\Session\Session;
use Exception;

/**
 * Class Auth
 * @package App\Libraries\Admin
 *
 * @property Session $session
 */
class Auth extends BaseAuth
{
	const ERROR_PASSWORD = 1;
	const ERROR_DISABLED = 2;

	protected $session_name = 'customer';

	/**
	 * @param string $email
	 * @param string $password
	 * @return SysCustomer
	 * @throws Exception
	 */
	public function auth(string $email, string $password)
	{
		$user = (new SysCustomers())->findByEmail($email);
		if (!password_verify($password, $user->password))
		{
			throw new Exception(lang('Auth.Error.password'), self::ERROR_PASSWORD);
		}
		if ($user->disabled)
		{
			throw new Exception("Auth.Error.disabled", self::ERROR_DISABLED);
		}

		$this->set($user);

		return $user;
	}

	/**
	 * @return SysCustomer
	 */
	public function user(): SysBaseUser
	{
		return parent::user(); // TODO: Change the autogenerated stub
	}

}