<?php

namespace App\Models;

use App\Entities\ImovelGallery;

/**
 * Class ImoveisGallery
 * @package App\Models
 */
class ImoveisGallery extends AppModel
{
    public    $table         = 'imoveis_gallery';
    protected $returnType    = ImovelGallery::class;
    protected $allowedFields = [
        'id',
        'imovel_id',
        'image',
        'order',
    ];

    public function findByImovel(int $id, bool $asArray = false): array
    {
        if ($asArray) $this->asArray();

        return $this->where('imovel_id', $id)->orderBy('order')->findAll();
    }

    /**
     * @param int|null $id
     * @return ImovelGallery
     */
    public function find($id = null)
    {
        return parent::find($id); // TODO: Change the autogenerated stub
    }


}